Repository googlefonts/fontra, pull requests merged in 2023-09, with the labels that each got.

#802 [context-menu] Choose item when release mouse after control-click and drag.
  src/fontra/client/web-components/menu-panel.js
Labels: cosmetic bug

#804 [ui-list] Improve scrollbars behaviour.
  src/fontra/client/web-components/ui-list.js
Labels: cosmetic bug

#806 Show scrollbars only if needed.
  src/fontra/client/web-components/designspace-location.js
  src/fontra/client/web-components/grouped-settings.js
  src/fontra/client/web-components/ui-form.js
  src/fontra/filesystem/landing.css
  src/fontra/views/editor/editor.css
  src/fontra/views/editor/panel-designspace-navigation.js
  src/fontra/views/editor/panel-selection-info.js
  src/fontra/views/editor/panel-text-entry.js
Labels: cosmetic bug

#801 [context-menu] Fix wrong items vertical margins and left padding.
  src/fontra/client/web-components/menu-panel.js
Labels: cosmetic bug

#815 Simplify list icon cells: remove redundant div
  src/fontra/views/editor/panel-designspace-navigation.js
Labels: code quality

#840 Automatically sort JavaScript imports using `prettier` plugin.
  .prettierrc
  package-lock.json
  package.json
  rollup.config.js
  src/fontra/client/core/canvas-controller.js
  src/fontra/client/core/font-controller.js
  src/fontra/client/core/glyph-controller.js
  src/fontra/client/core/var-model.js
  src/fontra/client/core/var-path.js
  src/fontra/client/web-components/add-remove-buttons.js
  src/fontra/client/web-components/designspace-location.js
  src/fontra/client/web-components/glyphs-search.js
  src/fontra/client/web-components/grouped-settings.js
  src/fontra/client/web-components/icon-button.js
  src/fontra/client/web-components/menu-panel.js
  src/fontra/client/web-components/modal-dialog.js
  src/fontra/client/web-components/range-slider.js
  src/fontra/client/web-components/ui-form.js
  src/fontra/client/web-components/ui-list.js
  src/fontra/views/editor/cjk-design-frame.js
  src/fontra/views/editor/edit-behavior.js
  src/fontra/views/editor/edit-tools-pen.js
  src/fontra/views/editor/edit-tools-pointer.js
  src/fontra/views/editor/edit-tools-power-ruler.js
  src/fontra/views/editor/editor.js
  src/fontra/views/editor/panel-designspace-navigation.js
  src/fontra/views/editor/panel-glyph-search.js
  src/fontra/views/editor/panel-reference-font.js
  src/fontra/views/editor/panel-selection-info.js
  src/fontra/views/editor/panel-text-entry.js
  src/fontra/views/editor/panel-user-settings.js
  src/fontra/views/editor/scene-controller.js
  src/fontra/views/editor/scene-model.js
  src/fontra/views/editor/sidebar.js
  src/fontra/views/editor/visualization-layer-definitions.js
  src/fontra/views/editor/visualization-layers.js
  test-js/test-change-recorder.js
  test-js/test-changes.js
  test-js/test-classes.js
  test-js/test-fit-cubic.js
  test-js/test-path-changes.js
  test-js/test-path-hit-tester.js
  test-js/test-rectangle.js
  test-js/test-utils.js
  test-js/test-var-funcs.js
  test-js/test-var-model.js
  test-js/test-var-path.js
Labels: enhancement, code quality, javascript

#854 Explicitly set "trailing comma" option value to avoid fallbacks to unexpected defaults.
  .prettierrc
Labels: enhancement, code quality, javascript
